name: Deploy Latest
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      sync:
        description: The action to take for the dev to main sync pull request
        required: true
        type: choice
        options:
          - create
          - install
permissions:
  contents: write
  pull-requests: write
jobs:

  create-sync-pr:
    if: github.event_name == 'workflow_dispatch' && inputs.sync == 'create'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
      - name: Create sync PR
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git checkout -b ci/sync-dev-to-main origin/main
          git rebase origin/dev
          git push -u origin HEAD
          gh pr create --head "ci/sync-dev-to-main" --base "main" \
            --title "chore: sync dev to main" \
            --body "This PR was automatically generated by the deploy-latest GitHub action" || true


  install-sync-pr:
    if: github.event_name == 'workflow_dispatch' && inputs.sync == 'install'
    runs-on: ubuntu-latest
    steps:
      - name: Install sync PR
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          gh repo edit --enable-rebase-merge --repo ${{ github.repository }}
          gh pr merge  ci/sync-dev-to-main --rebase --admin --repo ${{ github.repository }}
          gh repo edit --enable-rebase-merge=false --repo ${{ github.repository }}

  release-please:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          target-branch: main
      - name: Checkout Repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.ADMIN_TOKEN }}
          fetch-depth: 0
      - name: Sync release commit to dev
        if: ${{ steps.release.outputs.release_created }}
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git checkout -b ci/cherry-pick-release-commit origin/dev

          if ! git cherry-pick origin/main; then
            git checkout --ours "${{github.workspace}}/CHANGELOG.md"
            git checkout --theirs "${{github.workspace}}/version.txt"
            git cherry-pick --continue
          fi

          git push -u origin HEAD
          gh pr create --fill --head "ci/cherry-pick-release-commit" --base "dev"
